name = "andrewalba"
compatibility_date = "2025-07-15"
pages_build_output_dir = ".output/public"

[[d1_databases]]
binding = "DB"
database_name = "content-db"
database_id = "89e80c85-6355-4060-b4ec-9df6c9c56d04"
